from .bitfinex import Bitfinex
from .bitstamp import Bitstamp
from .bittrex import Bittrex
from .ccex import CCEX
from .coincheck import Coincheck
from .cryptopia import Cryptopia
from .gemini import Gemini
from .itbit import ItBit
from .kraken import Kraken
from .okcoin import OKCoin
from .rocktrading import RockTradingLtd
from .yunbi import Yunbi
from .poloniex import Poloniex
from .quoine import Quoine
from .quadriga import QuadrigaCX
from .gdax import GDAX
from .vaultoro import Vaultoro
from .hitbtc import HitBtc
from .bter import Bter
