"""Formatter Objects for interface classes."""
from bitex.formatters.base import APIResponse
from bitex.formatters.binance import BinanceFormattedResponse
from bitex.formatters.bitfinex import BitfinexFormattedResponse
from bitex.formatters.bitstamp import BitstampFormattedResponse
from bitex.formatters.bittrex import BittrexFormattedResponse
from bitex.formatters.ccex import CCEXFormattedResponse
from bitex.formatters.coincheck import CoinCheckFormattedResponse
from bitex.formatters.cryptopia import CryptopiaFormattedResponse
from bitex.formatters.gdax import GDAXFormattedResponse
from bitex.formatters.gemini import GeminiFormattedResponse
from bitex.formatters.hitbtc import HitBTCFormattedResponse
from bitex.formatters.itbit import ItBitFormattedResponse
from bitex.formatters.kraken import KrakenFormattedResponse
from bitex.formatters.okcoin import OKCoinFormattedResponse
from bitex.formatters.okex import OKexFormattedResponse
from bitex.formatters.poloniex import PoloniexFormattedResponse
from bitex.formatters.quadriga import QuadrigaCXFormattedResponse
from bitex.formatters.quoine import QuoineFormattedResponse
from bitex.formatters.rocktrading import RockTradingFormattedResponse
from bitex.formatters.vaultoro import VaultoroFormattedResponse
from bitex.formatters.bithumb import BithumbFormattedResponse
from bitex.formatters.coinone import CoinoneFormattedResponse
from bitex.formatters.cexio import CEXioFormattedResponse
from bitex.formatters.exmo import ExmoFormattedResponse
from bitex.formatters.coinnest import CoinnestFormattedResponse
from bitex.formatters.gateio import GateioFormattedResponse
