from .bitfinex import BitfinexREST
from .bitstamp import BitstampREST
from .bittrex import BittrexREST
from .bter import BterREST
from .ccex import CCEXRest
from .coincheck import CoincheckREST
from .cryptopia import CryptopiaREST
from .gdax import GDAXRest
from .gemini import GeminiREST
from .hitbtc import HitBTCREST
from .itbit import ItbitREST
from .kraken import KrakenREST
from .okcoin import OKCoinREST
from .poloniex import PoloniexREST
from .quadriga import QuadrigaCXREST
from .quoine import QuoineREST
from .rocktrading import RockTradingREST
from .vaultoro import VaultoroREST
from .yunbi import YunbiREST

